### ISSUE TITLE
[cancelled] Open Community Working Meeting 2021-12-16

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#125]
Open Community Working Meeting 2021-12-16 - 14:00 UTC

Zoom Meeting link: https://postman.zoom.us/j/82037276001

Agenda: Compiling!

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items  | @relequestual | 
| [TOPIC] [IssuePRDiscussion] | [owner] | 

AOB?
If you want to discuss any other business not on the agenda, please add comments during the meeting.
If we do not complete the agenda, your discussion item will likely be rolled over to the next call.

Action items:
- [ ]

Notes:

Agenda Items rolling over:
- list

Recording:

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!
