### ISSUE TITLE
Document the slack server's channel's topics

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#180]
While our [community Slack serve](https://json-schema.org/slack)r and the community is great, sometimes people come in and change the channel topics.
Sadly, Slack doesn't allow a way to prevent this from happening.

I did look into some automation to revert the channel topics should they get changed, however this turned out to be more difficult and the work is on hold.

However, there still needs to be a list of the channels and their current topics stored in this repo.
Currently only one is stored here: https://github.com/json-schema-org/community/blob/main/slack/channel-topics.json

The other channels along with their current topics should be added to that file.

**Comment by gregsdennis** [comment]
> Sadly, Slack doesn't allow a way to prevent this from happening.

It also doesn't tell you what the topic was changed _from_.

Do/can we have restrictions on who can create new channels?

**Comment by Relequestual** [comment]
> Do/can we have restrictions on who can create new channels?

We do! Only admins or owners.

**Comment by pranitb10** [comment]
@Relequestual Hey Ben, I would love to take up this issue and document all the channels along with their current topics in the above-mentioned JSON file. Can you please assign this to me?

**Comment by gregsdennis** [comment]
@pranitb10 no assignment necessary! 🙂  Thanks for stepping up!

If you just want to create a PR, we'll have a look and pull it in.

**Comment by pranitb10** [comment]
> @pranitb10 no assignment necessary! 🙂 Thanks for stepping up!
> 
> If you just want to create a PR, we'll have a look and pull it in.

Hey @gregsdennis , thank you! I have one query about what should I add to the topics for channels in the documentation for all those channels that do not have anything written in their channel topics?

**Comment by gregsdennis** [comment]
I say have fun proposing something.

**Comment by Relequestual** [comment]
@pranitb10 Sorry for the delay in responding. No assignment needed as Greg said. THanks for making a PR.

**Comment by pranitb10** [comment]
@Relequestual No worries, it's fine. The PR is approved. Would it be merged by the team/reviewers or do I have to merge it?

**Comment by benjagm** [comment]
I think we can close this issue as this is something we are already doing.

**Comment by gregsdennis** [comment]
This is done

https://github.com/json-schema-org/community/blob/main/slack%2Fchannel-topics.json

**Comment by benjagm** [comment]
Thanks @gregsdennis !
