### ISSUE TITLE
Document JSON Schema team members list as markdown in the community repo

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#211]

**Comment by jviotti** [comment]
Not something we have to do now, but it would be nice to start thinking about clearly documenting the process for somebody to become a member of JSON Schema. i.e. is a nominating + voting taking place, what is the minimum bar, etc?

**Comment by handrews** [comment]
And probably also a process for moving people to emeritus?  Some of those folks are no longer active with the project.  And for that matter, I don't know who some of them are at all.
