### ISSUE TITLE
Postman case study

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#215]

**Comment by jviotti** [comment]
@Relequestual Let me know what we should do to get this published!

**Comment by Relequestual** [comment]
Published.
Still needs to be converted into markdown and published on the JSON Schema blog.
I've been given permissions as long as we encode the canonical location back to https://blog.postman.com/how-postman-uses-json-schema/ (which I suggested anyway)

**Comment by jviotti** [comment]
Assigning to you @Relequestual as only the JSON Schema blog publishing step is remaining
