### ISSUE TITLE
Open Community Working Meeting 2022-08-08

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/community#219]
# Open Community Working Meeting 2022-08-08 - 14:00 PT

Zoom Meeting link: https://postman.zoom.us/j/89562933116?pwd=OWlsQ0RrcDY4S1JQU2d2Q2M0aFFlZz09

[Live minutes and notes doc](https://docs.google.com/document/d/1sDxT1Bge7ZHrl2XhigGsy_HR6yTXpr_V4Ql0tw-Io8A/edit#)

Agenda:

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review [last call](https://github.com/json-schema-org/community/issues/213#issue-1320747136)'s action items  | @gregsdennis |
| Media type registration update and status https://github.com/orgs/json-schema-org/discussions/198 | @jdesrosiers | 
| JSON Schema glossary page or site https://github.com/json-schema-org/community/issues/199 | @Julian |
| How to deprecate old versions https://github.com/orgs/json-schema-org/discussions/192 | @gregsdennis |

AOB?
If you want to discuss any other business not on the agenda, please add comments during the meeting.
If we do not complete the agenda, your discussion item will likely be rolled over to the next call.

Attendees:
- @Relequestual
- @awwright 
- @jdesrosiers 
- @gregsdennis 

Action items:
- Some really good discussion, but no action items

Notes:
- @awwright is continuing work on his forward-compatibility concept by adding some examples
- @jdesrosiers doesn't believe that @handrews' analysis stuff needs to be complete before continuing with media type registration, but we'll still wait for agreement.
- Discussion of deprecation of older drafts led to a discussion around the overall shape of JSON Schema as a specification and its future, leaning toward something that could be as maximally compatible with past versions.  This would require a commitment (that we've laxed on recently) to not include changes that would break older behavior.  @gregsdennis pressed that this doesn't address the primary issue of implementor burden.  This discussion continued for the remainder of the call and wasn't ultimately resolved.

Agenda Items rolling over:
- @Julian's effort with the glossary page.

Recording: [link](https://postman.zoom.us/rec/share/xUqNC7U2aJ6BHqk6nhCgkRmJPAQT2VXG_p0r5lMormkGE-XfVUx9x7MepNA5e9pf.mjqzOQjxs0zP8w8X?startTime=1659993238000)

**Comment by gregsdennis** [comment]
https://github.com/orgs/json-schema-org/discussions/217 more on boostrapping rules

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!
