### ISSUE TITLE
Checklists in PRs and GH Action propogation

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#232]
I've long thought about having an approach to manage and control GitHub Actions across org repos in a centralised way.

Today I saw a checklist in a PR, and the author didn't want the PR to be merged till all the items were checked. I looked, and found this: https://github.com/Shopify/task-list-checker

Then i rememberd, and thought, it could be neat to roll this out to multipe repos!

I looked and found this https://github.com/varunsridharan/action-github-workflow-sync

Then I also remembered https://github.com/derberg/copy-files-to-other-repositories - @derberg is a member of the AsyncAPI team, and they use this tool for the org.

In looking at the feature set again, it does seem to have improved, but I haven't fully evaluated the differences. I'm probably more inclined to use the solution we know we can get patched or updated if required, than that of someone we don't know.

I'll hopefully find some time to test this idea out soon!

**Comment by gregsdennis** [comment]
I'm pretty sure I did this somewhere.  Maybe I tried to add it here, but we weren't ready for it.

As an additional suggestion, I have a [dependencies check action](https://github.com/gregsdennis/dependencies-action) that can be used to ensure that dependent issues and PRs are resolved.  I use this in `json-everything`.

**Comment by aialok** [comment]
If available, I would love to work on this issue. Please assign : )

**Comment by gregsdennis** [comment]
@aialok I'm not sure there's actually anything to do. I have a PR for this already somewhere. 

We really just need to make a decision as to whether we want this, which is an admin thing.

**Comment by aialok** [comment]
okie okie....thanks @gregsdennis : )

**Comment by gregsdennis** [comment]
Given the above PR and issue, I'm going to close this as a duplicate.
