### ISSUE TITLE
[cancelled] Open Community Working Meeting 2022-10-24 - 14:00 PT

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#255]
# Lack of agenda, so this meeting is cancelled.

# Open Community Working Meeting 2022-10-24 - 14:00 PT

Zoom Meeting link: https://postman.zoom.us/j/89562933116?pwd=OWlsQ0RrcDY4S1JQU2d2Q2M0aFFlZz09

Agenda: Compiling!

| Topic | Owner | Decision/NextStep |
| -- | -- | -- |
| Review last call's action items  | [facilitator] |
| [TOPIC] [IssuePRDiscussion] | [owner] |

AOB?
If you want to discuss any other business not on the agenda, please add comments during the meeting.
If we do not complete the agenda, your discussion item will likely be rolled over to the next call.

Action items:
- [ ]

Notes:

Agenda Items rolling over:
- list

Recording: [link]

**Comment by benjagm** [comment]
Closing this issue as all tasks are completed. Thanks for your contributions!
