### ISSUE TITLE
Add a community announcements Slack channel

### ISSUE THREAD

**Issue by Gdewilde** [json-schema-org/community#30]
Linked conversation: https://json-schema.slack.com/archives/C01UAR49N0M/p1626364399012000?thread_ts=1626363995.011600&cid=C01UAR49N0M

**Comment by Relequestual** [comment]
In addition to creating a channel, this would require a PR to https://github.com/json-schema-org/community/tree/main/slack

**Comment by benjagm** [comment]
Is it OK if I create the channel with this name: `#community-announcements` as a default channel to all the users of the workspace?

**Comment by Relequestual** [comment]
I think this is OK, yes. I don't think we add all current users to the channel, but we can use `#announcments` to let them know it was created.

**Comment by Relequestual** [comment]
@Gdewilde This is now done. Thanks to @benjagm!
