### ISSUE TITLE
Website Analytics 

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#300]
**Open Community Weekly Meeting:** 2023-01-16

**Work Summary**:
In the past Open Community Working Meeting 2023-01-16 #294, we concluded that [Plausible](https://plausible.io/) might be a great enhancement of the current analytics of the Website.

As a result, a new action was captured owned by @Relequestual with the purpose of gathering feedback from the Community before we proceed with this or any other tool.

Completing this work will mean we have checked with the Community that there are no risks, cons, or better alternatives. For more context please check #294 notes and recording.

**Comment by Relequestual** [comment]
While Cloudflare offer free web analytics, it is limited to 6 months retention, which is not ideal!

Plausible is open source, and the cost would be £49 a month.
I think this is a fair price.
We get over 200k page views, but less than 500k page views, per month. That's the price for their 500k tier.

**Comment by benjagm** [comment]
> Plausible is open source,

Sounds great. Can we proceed with the account creation?

**Comment by benjagm** [comment]
I just created an account in plausible.  It is a free/trial account and we'll complete the setup as soon as we lunch the new website to the https://json-schema.org/ domain.
