### ISSUE TITLE
Usage of "agenda" label to get PRs and Issues automatically added to the Open Community Weekly Meetings agenda.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#301]
**Open Community Weekly Meeting:** 2023-01-16

**Work Summary**:
In the past Open Community Working Meeting 2023-01-16 #294, we agreed on the usage of a new "agenda" label for tagging PRs or issues to be discussed in the meeting

As a result, a new action was captured owned by @benjagm with the purpose of building a GitHub automation to add the tagged issues/PRs as agenda items of the Open Community Weekly Meetings. For more context please check #294 notes and recording.

**Context:**
JSON Schema Community is running an Open Community Weekly Meeting every Monday. For every meeting, a new issue is created 6 days before the meeting using the OCWM template, and during that time, everyone in the community is free to add new topics to the agenda. With this feature, we can make it easier to include PRs to be discussed as part of the agenda without having to do all the work manually.

**Automation trigger:**
Every time someone adds the label "agenda" to a PR, that PR should be included in the agenda of the upcoming OCWM.

**Outcome**
A new item will be added to the agenda, the PR will be added to the Topic column and the author to the Owner column.

Completing this work will mean the automation has been built, tested, and communicated among the community.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Work Detail**:

- [x] Gather sample actions with a similar purpose.(@0xSudarshan)
- [x] Minimum requirements.(@0xSudarshan)
- [x] Development.(@0xSudarshan)
- [x] Test. (@0xSudarshan)
- [x] Install in JSON Schema organizacion (@benjagm)
- [x] Ready.
- [x] Communicated to the Community.

**Any further requirements to resolve this issue**

**Comment by Relequestual** [comment]
The OpenJS Foundation uses https://github.com/nodejs/create-node-meeting-artifacts
We may not want to copy all of it, but some of it may be useful.

**Comment by benjagm** [comment]
Other resources: 
-  https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
- https://github.com/marketplace/actions/select-matching-issues

**Comment by benjagm** [comment]
A great next feature to implement from here is to automatize 1)the messages to slack and 2) to social media to promote new Open Community Weekly Meetings.

**Comment by 0xSudarshan** [comment]
One possible solution would be to configure Webhooks in every repository and whenever there is a pull request with a particular label , we trigger a workflow that updates the `open_community_working_meeting.md` template ,  but that would propose changes to the  template and someone has to merge the pull request each and every time.

**Comment by 0xSudarshan** [comment]
One possible solution would be to configure Webhooks in every repository and whenever there is a pull request with a particular label we trigger a workflow that edits the existing issue with the newly raised PR as well as author of the PR but the problem is only  issue owners and users with push access can edit an issue

**Comment by benjagm** [comment]
Congrats for the great research @0xSudarshan . This is a great starting point but there are some clarifications needed.
* Trigger: The trigger should be the "labeled" action over the "pull_request" event. More info [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
* The destination file to add the labeled PRs details should be the agenda issue of the upcoming OCWM.

The next step in my opinion might be to build and try this in a testing repo.

**Comment by Relequestual** [comment]
We might need to modify this issue, as I haven't found anything that supports org wide action triggers without using a webhook, which isn't ideal.

What might be preferable is to have an action which runs on a schedule to collect Issues and PRs from the org with the required label, and then replaces the right part of the template in the latest OCWM issue.

Would be best to do this in a test org.

**Comment by Relequestual** [comment]
@0xSudarshan I think you are looking for these details: https://docs.github.com/en/actions/security-guides/automatic-token-authentication ?

Also worth noting that there are a load of existing examples you can look at : https://github.com/actions

**Comment by 0xSudarshan** [comment]
@Relequestual I am going to change my approach as to what u said . I was in an assumption that we will be implementing this to all  repositories that come under this organisation so thought Webhooks would be the way to go since it supports org level triggers and there wouldn't  be any need for us  to create it in individual repos .(I will avoid using using webhooks)  and as you mentioned there aren't any org wise  action triggers we need to set up actions in individual repository . I don't think we need a scheduler tho , we could just update the **latest** OCWM issue with the PR and the author name when an action is triggered if that makes sense

**Comment by gregsdennis** [comment]
> I haven't found anything that supports org wide action triggers without using a webhook - @Relequestual 

I found https://blog.marcnuri.com/triggering-github-actions-across-different-repositories during the [meeting](https://github.com/json-schema-org/community/issues/294).

**Comment by Relequestual** [comment]
> > I haven't found anything that supports org wide action triggers without using a webhook - @Relequestual
> 
> I found https://blog.marcnuri.com/triggering-github-actions-across-different-repositories during the [meeting](https://github.com/json-schema-org/community/issues/294).

That's cool, but we need a "trigger", not "triggering".
Webhooks would be the only viable way to proxy such, but I think an alternative approach would be better.

**Comment by Relequestual** [comment]
> ... I don't think we need a scheduler tho , we could just update the **latest** OCWM issue with the PR and the author name when the workflow is triggered in a particular repo that has a pr with the label "agenda" - @0xSudarshan 

It needs to be Issues, PR's, and Discussions, across the org, but with the ability to exclude specific repos.

In fact, I think just making sure only PUBLIC repos are considered should be enough. We just don't want to automatically do anything based on anything in private repos in the org.

The workflow could be run manually. This would enable us to choose to run it or not depending on if the meeting is happening. We could modify the Issue template for the meeting to include a link to the workflow. We will need to modify it anyway to include a placeholder.

**Comment by 0xSudarshan** [comment]
@Relequestual @benjagm  @gregsdennis  :
1. We create a workflow which triggers when a PR/issue/discussion is raised under the label "agenda"
2. The above can be be setup in public repos we need 
3. We create another workflow in separate repository just like https://github.com/nodejs/create-node-meeting-artifacts that gets triggered when 1. gets triggered (this can be done using repository_dispatch - https://blog.marcnuri.com/triggering-github-actions-across-different-repositories  )and make sure the workflow  runs node js scripts to update the latest OCWM issue. 
Let me know if this sounds reasonable ?

**Comment by benjagm** [comment]
I agree with @Relequestual on the benefits of triggering the workflow manually.
@0xSudarshan lets follow the approach of building the logic in node.js like https://github.com/nodejs/create-node-meeting-artifacts to make it easier to modify the issue. 

To make it easier to add the information to the PR we just need to add a placeholder (like https://github.com/nodejs/create-node-meeting-artifacts).

**Comment by 0xSudarshan** [comment]
@Relequestual @benjagm I have built the workflow and added it to [https://github.com/0xSudarshan/automated-artifacts-build](url).

**Comment by joesepi** [comment]
The Node.js project and the OpenJS Foundation have been wanting to move away from `create-node-meeting-artifacts` and started work in this repo. I would be happy to work with anyone to continue moving this forward. ✌️ 
https://github.com/pkgjs/meet

**Comment by 0xSudarshan** [comment]
@joesepi let me know what i can do to help . I am happy to help you guys

**Comment by benjagm** [comment]
Hi @joesepi . For the final solution we are not using the same approach than `create-node-meeting-artifacts`, @0xSudarshan has built a Github action that is going to be much easier to maintain. The initial version has to be triggered manually and it will add PRs and Issues properly labeled to the upcoming weekly meeting.

I do see https://github.com/pkgjs/meet as a great next step to our automations because I am creating the issues for the weekly meetings manually and having them scheduled will save a lot of time.

**Comment by benjagm** [comment]
Quick update: I am planning to add the code to the [Community](https://github.com/json-schema-org/community) repo and setup everything tomorrow.

**Comment by benjagm** [comment]
Hi @0xSudarshan. I started the integration and testing of the Github action inside the Community repository using this fork: https://github.com/benjagm/community

Unfortunately I wasn't able to make it work. Find below the current error I am getting:
https://github.com/benjagm/community/actions/runs/4418460663/jobs/7745616217

Any idea about what might be happening? What happens if there is no OCWM created?

**Comment by 0xSudarshan** [comment]
@benjagm please label your OCWM issue with `Working Meeting` just like we do it in our community repository in this organisation
<img width="680" alt="Screenshot 2023-03-16 at 12 31 08 AM" src="https://user-images.githubusercontent.com/103627996/225415556-b382d1fa-62d7-4a67-a467-1a437bd5560e.png">

**Comment by benjagm** [comment]
Thanks! I did it but the issue persist.

In case of not finding any OCWM issue, the expected behaviour is successful execution.
In case of finding any PR or issue labeled the expected behaviour is successful execution too.

In both cases it may be helpful adding some echo messages like "There is no OCWM available" or "There are no items labeled".

Could it be possible to add the label name as repository variable?

**Comment by 0xSudarshan** [comment]
Makes sense will do the above and revert back

**Comment by benjagm** [comment]
Hi @0xSudarshan finally I was able to complete the integration and testing of the Github action and is available in the branch/folder: https://github.com/json-schema-org/community/tree/benjagm-githubaction-agenda-items/operations/actions/automated-artifacts-build

I have done some changes in the code:
- Adapt folders setup to run into Community repo.
- Remove unnecessary file.
- Refine the documentation.
- Small changes in the placeholder replacement algorithm.

Yo have done an amazing job and now only the PR approval is pending.

**Comment by benjagm** [comment]
I just started to receive some feedback in the #368 and there are 2 elements to consider:
* We have an 8K index.js file with a lot of unnecessary code that will require a deep cleaning.
* There is a [new beta feature](https://github.blog/changelog/2023-01-10-github-actions-support-for-organization-wide-required-workflows-public-beta/) to apply a github action in multiple repos of the same org. This can help us to avoid the index.js file complexity.

I am working in a new version of the action and I'll love to get your feedback as soon as I have a first version @0xSudarshan .

**Comment by benjagm** [comment]
I updated the github action to make use of all the js code but embedded in the github action yaml by using actions/github-script@v6.

The PR is updated.

**Comment by benjagm** [comment]
You made all the heavy lifting, I just adapted the code to actions/github-script. TEAM WORK!

I discovered actions/github-script working in other community actions and adapted this one for consistency.

Are you thinking in your next contribution? We have great issues in [Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues) and [Bowtie](https://github.com/bowtie-json-schema/bowtie/issues). @Julian is the maintainer of both projects and is an awesome mentor.

**Comment by Relequestual** [comment]
@benjagm could you update https://github.com/orgs/json-schema-org/discussions/35 to note that people can label issues and PRs with `agenda` please?
Then I think we can close this issue =]

**Comment by benjagm** [comment]
> could you update https://github.com/orgs/json-schema-org/discussions/35 to note that people can label issues and PRs with `agenda` please?

Thanks for the reminder @Relequestual . I updated the PR, the OCWM issue template and I'll remind this feature to the Community.
