### ISSUE TITLE
GSoC: OpenAPI pre v3.1 JSON Schema support in Alterschema

### ISSUE THREAD

**Issue by jviotti** [json-schema-org/community#316]
**Project title**

OpenAPI pre v3.1 JSON Schema support in [Alterschema](https://github.com/sourcemeta/alterschema)

**Brief Description**

OpenAPI, before a certain version, used a variant of JSON Schema that is not 100% compliant with the specification. Alterschema is an open-source tool to automatically upgrade schemas across versions of the JSON Schema specification. The intention of this idea is to extend Alterschema with support for upgrading old OpenAPI JSON Schema definitions to JSON Schema 2020-12.

**Expected Outcomes**

Add a new set of transformation rules to Alterschema for upgrading old OpenAPI JSON Schema definitions to JSON Schema 2020-12

**Skills Required**

- JSON
- JSON Schema
- OpenAPI

**Mentors**

@jviotti 

**Expected Difficulty**

Easy/Medium.

**Expected Time Commitment**

175 hours.

**Comment by karenetheridge** [comment]
Wouldn't some experience in Javascript be required too?

**Comment by benjagm** [comment]
I'll suggest closing this Issue because our GSoC application was rejected.

**Comment by benjagm** [comment]
We'll consider this idea for the 2024 edition.

**Comment by jviotti** [comment]
I'm closing this proposal in favor of increasing its scope in https://github.com/json-schema-org/community/issues/599 as discussed in the previous community meeting.
