### ISSUE TITLE
GSoC: Data Transformation Utilities Using JSON Schemas

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/community#318]
Data Transformation Utilities Using JSON Schemas

**Brief Description**
JSON Schema is designed for validation, but the information in a schema can be used to for a number of other purposes. One of those purposes is data transformation. This 

**Expected Outcomes**

Provide an implementation of the following utilities in any language. They should work with at least the latest version of JSON Schema. Tests should be described in JSON so others who want to write a similar tool in a different language can easily use your tests to ensure compatibility.

* Provide a utility that takes a JSON Schema and a JSON document and adds to the document any values that are missing but have a `default` specified for that value in the JSON Schema.
* Provide a utility that takes a JSON Schema and a JSON document and removes properties in the JSON document that are not described in the JSON Schema.
* Provide a utility that takes a JSON Schema and a query string from a form post (`application/x-www-form-urlencoded`) and convert the string to JSON using the JSON Schema to know the types for the values.
  * For example, the string `?foo=1` with schema `{ "properties": { "foo": { "type": "number" } } }` should return `{ "foo": 1 }` rather than `{ "foo": "1" }`.

**Skills Required**

* A basic understanding of JSON Schema

**Mentors**
@jdesrosiers 

**Expected Difficulty**
Easy

**Expected Time Commitment**
175

**Comment by benjagm** [comment]
Closed and replaced by: https://github.com/postman-open-technologies/gsoc-2023/issues/16
