### ISSUE TITLE
Let's automate some Community operations

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#373]
## Context
The JSON Schema community has been growing rapidly in recent years, and as a result, our community operations have become more complex. While we've made strides in improving our processes and communication, there is always room for improvement. To that end, We'd like to start a discussion around identifying suitable automations that could help us to focus on generating value for JSON Schema.

## What to automate?
We invite everyone to suggest automations that could help to improve our community operations. Whether it's automating repetitive tasks or implementing new features, we are open to all suggestions. Let's work together to make our community more efficient and inclusive!

When suggesting automations, please try to include the following information:
- A brief description of the automation.
- How the automation will improve our community operations.

## List of automations
Find below the list of automations identified:
- [x] #368 
- [x] #372 
- [x] #371 
- [x] #637
- [x] #638
- [x] Notify in slack when a new meeting is scheduled.
- [x] #639

## How to Suggest Automations
To suggest an automation, please create a comment in this thread with a brief description of the automation, and how it will improve our community operations. Please keep in mind that we will need to review and prioritize with focus on those that will have the most significant impact.

Thank you for your help in improving our community operations!

**Any further requirements to resolve this issue**

**Comment by gregsdennis** [comment]
> Notify in slack when a new meeting is scheduled.

I think this can be added to (or at least triggered by) the Action to create the meeting issues.

**Comment by benjagm** [comment]
> > Notify in slack when a new meeting is scheduled.
> 
> I think this can be added to (or at least triggered by) the Action to create the meeting issues.

Agreed. It can be a new step in that action.

**Comment by Abhinav-Saxena-dev** [comment]
Hello @benjagm. I like the idea of sending slack notifications for community benefit and would like to take this up! Can you please assign this to me? 

Also, I'd appreciate any guidance you think would prove helpful while working on this! 

Thank you!

**Comment by benjagm** [comment]
> Slack notifications before

Can you please describe what approach you suggest to send notifications consistently?

**Comment by benjagm** [comment]
@Relequestual Can you please what approach are we using for getting Github notifications in `gitub` and `ghd-cummunity` channels?

**Comment by Abhinav-Saxena-dev** [comment]
@benjagm Sure.
### Approach for PR notification:
- Add a new WebHook or edit the existing one to support Pull Request events.
- create a WebHook handler or use the existing one ( assuming it exists as we already send notifications on some channels ) 
- Add corresponding body / notification content for each type of event such as PR opened, merged, etc.
- From inside the handler, we will execute a Post request to the slack WebHook URL and the specific channel.
- I suggest the body to be as: PR Number< Hyperlinked PR URL>: PR Title

### Approach for Failed GitHub Action Notification:
- We can use [notify-slack-notification](https://github.com/marketplace/actions/notify-slack-action) by modifying the actions workflow.

### Approach for new Video added on Channel
- Use YouTube Data API and subscribe to Push notifications.
- I suggest using [Google PubSubHubbub Hub](https://pubsubhubbub.appspot.com/subscribe) for this and set expiration to never or desired duration.

CC: @Relequestual

**Comment by Relequestual** [comment]
> @Relequestual Can you please what approach are we using for getting Github notifications in `gitub` and `ghd-cummunity` channels?

Hey @benjagm, we document this in the [Infastructure file](https://github.com/json-schema-org/community/blob/main/INFRASTRUCTURE.md#bots). If any changes/additions are made, let's make sure to update the documentation.

This currently reads the following:

> The #github channel bot uses the official Github Slack app, and runs all Github events from all of our repositories, apart from GitHub Discussions.
> 
> The #ghd-community channel bot uses Zapier to process webhooks for our Community repo's GitHub Discussions, and relay to Slack. The Zapier account is owned and paid for by Postman. If this ever might become a problem, we should move to our own licence. At the time, there was no official app integration.

**Comment by lmgyuan** [comment]
Hi, @benjagm I'm proposing the integration of a GitHub Action that automatically assesses the size of pull requests and assigns a corresponding label—XS, S, M, L, XL, XXL. This addition will aid reviewers in quickly gauging the scope of the PR.

**Comment by benjagm** [comment]
> Hi, @benjagm I'm proposing the integration of a GitHub Action that automatically assesses the size of pull requests and assigns a corresponding label—XS, S, M, L, XL, XXL. This addition will aid reviewers in quickly gauging the scope of the PR.

Thanks @lmgyuan I think that makes sense for well stablished engineering teams but here we are just contributors so I am not sure this will add value for us. In any case it is a great idea.

**Comment by benjagm** [comment]
I think it is ok to close this issue as completed and moving forward continue creating individual automation issues. Thanks everyone for your collaboration!
