### ISSUE TITLE
JSON Schema public email addresses

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#393]
## Context
I have noticed that we don't have any email address using the official JSON Schema domain. In addition, we haven't discuss what public email addresses we need and who should access those address. 

Find below some examples of situations where we may need a JSON Schema email address:
 - Email to report CoC violations. 
 - Generic email address.

This is an opportunity to improve the Community experience.

## Work to be done
The purpose of this issue is:
- [x] Decide the public email accounts we need.
- [x] Create the accounts and update the documentation and website accordingly. info@ report@ account have been created.
- [x] Decide who will access each one.
- [x] Update docs with new emails.

## Next steps
Please join the discussion and help us by:
 - Suggesting email addresses.
 - Suggesting who access each address.
 - Sharing other ideas

**Comment by Relequestual** [comment]
From the closed issue...
> I'm hoping that once we join the OpenJS Foundation, they will provide us with a mail server, which we can then configure. I shouldn't be directing json-schema.org mail to my mail server.

**Comment by benjagm** [comment]
Considering that we should pay this our shelves we need to find some providers to compare prices: 

- Mailfence:  https://mailfence.com/#pricing
- Ionos: https://www.ionos.com/office-solutions/create-an-email-address#plans

**Comment by Relequestual** [comment]
Currently NameCheap has a deal for email hosting.

> £9.72/year with a promo code - Renews for £12.18/year

Google Workspace would cost £6 a month (or £5 a month if paid yearly).

**Comment by benjagm** [comment]
We'll create 1 account info@json-schema.org and 1 alias:
- report@json-schema.org

We can use info@ for the newsletter.

**Comment by benjagm** [comment]
The account as been created and paid in mailfence.com. Now we need to complete the domain setup.

**Comment by benjagm** [comment]
The domain setup is completed and the accounts have been created. Now we need to decide who can access each.

**Comment by benjagm** [comment]
I just sent 2 PRs to update the email in the site and repositories:
- Landing page: https://github.com/json-schema-org/website/pull/234
- CoC reports: https://github.com/json-schema-org/.github/pull/15

**Comment by benjagm** [comment]
Closed as completed.
