### ISSUE TITLE
Refine the contributor journey

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#410]
We identified that it was a challenge for contributors to know how to contribute to projects both inside and outside of the GitHub organization.

@benjagm to define define success criteria, deliverables, and breakdown of tasks.

Assessed as medium-high impact/high effort during our [collaborators summit 2023](https://github.com/orgs/json-schema-org/discussions/391).

# Scope 
The scope of this project includes:
 - Identify the affected repositories inside and outside the github organization.
 - Assess the current state of the contributor journey.
 - Refine the contributing template.
 - Refine the contributing guidelines to make them consistent and provide a way to naturally navigate from one to another project.
 - Adapt the website and slack contribution experience to the enhanced version on Github.
 - Improve the recognition system.

# Objectives
The objectives of this project are:
 - Reduce friction for new contributors.
 - Increase the total number of contributors.
 - Provide clarity on the total number of contributors including non-code contributions and repositories outside the organization.
 - Increase the number of PRs and issues.
 - Increase the number of closed issues. 

# Plan
 - [x] Research
    - [x] #425
    - [x] Identify the list of contribution types of contribution. This is the prioritized list.
      1) Sponsors
      2) Adopters
      3) Website development
      4) Documentation
      5) Blogs posts
      6) Case Studies
      7) Community Management e.g. CoC Committee
      8) Spec development
      9) Bowtie development
      10) Test Suite development
      11) Design
      12) Answer questions
      13) TSC
    - [x] #508

 - [x] Implementation
    **Asses and enhance Contributor Journey for each type of contribution** doing the following:
    Issues will be created for each type.
    This is the list of actions to complete for each type:
      - Review the Readme or equivalent. 
      - The main place with the link to contribute.
      - Repo shield badges.
      - Review the contributing guide or equivalent and improve if necessary
      - All contributors are visible and aligned
      - Review all the places where this contribution path is enabled and make it consistent
      - Issues are triage and label issues
      - Issues are easy to find and progress is easy to follow.
      - Identify and create workflows to thank and congratulate contributions
      - Update the contribution experience handbook.
      
    Issues by type:
    - [x] #509
    - [x] Org wide contributing
    - [x] #550
    - [x] #583
    - [x] #551 
    - [x] #556 
    - [x] Bowtie contribution experience.
    - [x] Test suite contribution experience.
    
 - [ ] Metrics
    - [ ] Confirm the decided metrics.

# Success Metrics
The metrics for measuring the success of the documentation project includes:
 - \## New sponsors.
 - \## New adopters.
 - \## New case studies.
 - \## New guest blog posts.
 - +##% YoY Number of contributors.
 - +##% YoY Number of PRs and issues.
 - +##% YoY Number of closed issues. 
 - -##% YoY contributors' churn rate.

# Risks
The risks associated with this project includes:

**Comment by benjagm** [comment]
As peer the last OCWM #429 :
@benjagm to add action item to define success metrics.

**Comment by benjagm** [comment]
I decided to divide the scope of this task and take to issue #634 all the task related to the recognition system.

**Comment by benjagm** [comment]
This issue is now completed.
