### ISSUE TITLE
Create TSC Slack channels and archive private "collaborators" Slack channel

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#414]
While there wasn't a GitHub Discussion, we seemed to reach a loose consensus in a PR related to a discussion on a call.
**GitHub Discussion:** https://github.com/json-schema-org/community/pull/388

**Summary**: We have had a private channel on slack for collaborators for a long time. Much of the discussion in there could be public, but we have grown used to using it when we don't need to. We should strive to be more open.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

~~Yes~~/No
It is not a significant change.

**Required to resolve**

Amend Slack channels, including in the community repo [Slack folder](https://github.com/json-schema-org/community/tree/main/slack).

- [ ] Make PR in the community repo to create a `tsc-discussion` Slack channel. Must note that approving the PR also implies approval of creating `private-tsc-discussion` and archiving `collaborators`.
- [ ] Check other files in the Slack folder to see if they require updates
- [ ] Once PR is approved and merged, apply updates to Slack

**Comment by benjagm** [comment]
Sounds good to me.

**Comment by Julian** [comment]
Yep same.
