### ISSUE TITLE
Build the JSON Schema Community Metrics Dashboard/Dashboards

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#443]
**Summary:**
As part of enhancing the JSON Schema community's collaboration and visibility, we need to develop a comprehensive Metrics Dashboard. This dashboard will provide valuable insights into the community's growth, engagement, and impact by analyzing key metrics and presenting them in a user-friendly and visually appealing format. The goal is to empower the community members, contributors, and stakeholders with actionable data that can inform decision-making, improve resource allocation, and foster a thriving ecosystem around JSON Schema.

**Description:**
The JSON Schema community has experienced significant growth and adoption in recent years, with numerous individuals and organizations actively contributing to its development. To harness the potential of this vibrant community, we need to create a Metrics Dashboard that aggregates and visualizes essential data points.

The Metrics Dashboard will serve multiple purposes:

* Community Growth: The dashboard will provide insights into the growth of the community, including the number of active contributors, new members, and organizations involved. These metrics will help us understand the community's reach and assess its trajectory over time.
* Engagement Analysis: Tracking engagement is crucial to evaluate the community's health and involvement. The dashboard will present data on activities such as forum discussions, issue tracking, code contributions, and documentation updates. By analyzing these metrics, we can identify areas of high engagement and potential bottlenecks that require attention.
* Impact Assessment: The dashboard will enable us to measure the impact of the JSON Schema community by tracking the adoption of the standard in various projects and industries. This data will highlight success stories, identify influential users, and showcase real-world use cases, ultimately strengthening the community's credibility.

**Jobs to be done:**
- [ ] Decide the metrics.
- [ ] Decide the tools.
- [ ] Build the dashboard/dashboards.
- [ ] Promote and get feedback.

**Comment by benjagm** [comment]
LFX Insights dashboard: https://insights-v2.lfx.linuxfoundation.org/ojsf-json/trends

**Comment by Relequestual** [comment]
While we currently use and have some data in [Orbit](https://app.orbit.love), after seeing a demo from Microcks, we should find out if we can get free Open Source access to [Common Room](https://www.commonroom.io)

**Comment by benjagm** [comment]
Quick update on this. We are testing Common Room and it has a great reporting tool. As soon as we can apply to get Open Source benefits we will share the dashboard and mark this as completed.

**Comment by benjagm** [comment]
Closed as not planned. We'll use Common Room.
