### ISSUE TITLE
Proposal: JSON Schema Ecosystem Metrics

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#518]
### Background and Rationale

JSON Schema is a fundamental technology massively used in the industry, however it is not easy to measure its usage and adoption because is not a tool or service, instead is a specification with hundreds of implementations and countless use cases. This difficulty to measure the Ecosystem can affect our ability to generate trust and to attract sponsors and partners.

This proposal aims to define a framework for collecting, analyzing, and reporting relevant Ecosystem metrics.

### Proposal
- GitHub projects using JSON Schema topics.
  - Total number of projects.
  - Total number of stars.
  - Total number of contributors.
  - Total number of forks.
  - Total number of dependant projects.

- Github projects using any of the implementations listed on the implementers page.
  - Total number of projects.
  - Total number of stars.
  - Total number of contributors.
  - Total number of forks.
  - Total number of dependant projects.

- Data of the Top 5 projects by language. 

- We will add to this the adopters that are self-reporting in our adopters file.

- It would be great to be able to group the results by programming language.

### Implementation Plan

We plan to implement these metrics by:
- Developing a set of data collection tools and scripts using the GitHub API.
- Regularly reporting the metrics to the community through a dedicated dashboard or report.

Some ideas of similar projects:
- https://github.com/ansible-community/stats-crawler
- https://github.com/camunda-community-hub/stats-crawler
- https://github.com/mapbox/github-stats-collector

We invite the community to participate in the discussion and contribute to this effort. Your feedback and collaboration are essential to the success of this initiative.

### Collaboration and Volunteers

If you're interested in collaborating on this project or have skills in data analysis, tool development, or project management, please express your interest in the comments. We welcome all forms of collaboration and support.

This issue serves as a starting point for discussion and collaboration. Let's work together to define and implement ecosystem metrics for JSON Schema that will benefit the entire open-source community.

**Comment by Julian** [comment]
In case it helps, the hack for number of contributors is to set `per_page` to 1 and then look at the last page.

E.g. here with the CLI for the first result in the topic, with some silly Link header parsing:

⊙  gh api 'https://api.github.com/repos/tiangolo/fastapi/contributors?per_page=1' --include -X HEAD | rg -o '<.*page=(\d+)>; rel="last"' -r '$1'
464

Obviously some other stuff is available in the CLI too.

```
⊙  gh repo view json-schema-org/json-schema-spec --json forkCount,stargazerCount,watchers
{
  "forkCount": 261,
  "stargazerCount": 2959,
  "watchers": {
    "totalCount": 101
  }
}
```

I'll look to see about the rest of the data, a bunch more should be fairly easily retrievable.

**Comment by benjagm** [comment]
With all the info provided by Julian the only pending element are the dependant projects but that will require web-scraping or  using another tool like https://pypi.org/project/github-dependents-info/ because that is not provided by the api:

This is the information I am looking for but aggregated:
https://github.com/ajv-validator/ajv/network/dependents

**Comment by Julian** [comment]
It does indeed initially seem like that dependency data isn't available via API... :/

**Comment by jdesrosiers** [comment]
Do we know how "dependents" is calculated? It might be more or less useful depending on how it works. For example, ajv is used by eslint. Would every project that uses eslint be considered a dependent? That would create a lot of noise making it not a very useful metric.

**Comment by Julian** [comment]
AFAIK how it's calculated is language/tooling specific (e.g. in Python there was a long running issue about supporting pyproject.toml files which affected numbers IIRC). That one was finally fixed a few months ago. So what's in there is best-current-effort essentially on what GitHub supports. Further detail I'm sure is in the GH Docs.

IME it's indeed very noisy and not very useful, I essentially never look at it for my own repos -- but all this obviously depends on what question someone's trying to answer. But it's what's there, and I assumed the hope was maybe we could find some signal in the noise anyhow.

**Comment by benjagm** [comment]
I managed to create a python script to aggregate by language information from the api and the dependencies using web scrapping.

This is the resulting format:
```
{
    "total-dependents": 81474170,
    "total-stars": 269301,
    "Total total-repositories": 900,
    "Languages": {
        "Python": {
            "total-dependents": 1117941,
            "total-stars": 126395,
            "total-repositories": 114
        },
        "TypeScript": {
            "total-dependents": 57778918,
            "total-stars": 81296,
            "total-repositories": 169
        },
        "Java": {
            "total-dependents": 4282,
            "total-stars": 10391,
            "total-repositories": 53
        },
        "JavaScript": {
            "total-dependents": 22549621,
            "total-stars": 30310,
            "total-repositories": 237
        },
        "Clojure": {
            "total-dependents": 0,
            "total-stars": 2337,
            "total-repositories": 5
        },
        "Go": {
            "total-dependents": 3309,
            "total-stars": 5901,
            "total-repositories": 48
        },
        "Rust": {
            "total-dependents": 12576,
            "total-stars": 811,
            "total-repositories": 12
        },
        "C++": {
            "total-dependents": 103,
            "total-stars": 1857,
            "total-repositories": 14
        },
        "C#": {
            "total-dependents": 3350,
            "total-stars": 896,
            "total-repositories": 8
        },
        "PHP": {
            "total-dependents": 1841,
            "total-stars": 2880,
            "total-repositories": 50
        },
        "Swift": {
            "total-dependents": 0,
            "total-stars": 477,
            "total-repositories": 2
        },
        "Ruby": {
            "total-dependents": 1901,
            "total-stars": 1229,
            "total-repositories": 31
        },
        "HTML": {
            "total-dependents": 73,
            "total-stars": 471,
            "total-repositories": 14
        },
        "Vue": {
            "total-dependents": 145,
            "total-stars": 719,
            "total-repositories": 15
        },
        "CMake": {
            "total-dependents": 0,
            "total-stars": 225,
            "total-repositories": 1
        },
        "Shell": {
            "total-dependents": 0,
            "total-stars": 503,
            "total-repositories": 8
        },
        "Prolog": {
            "total-dependents": 10,
            "total-stars": 143,
            "total-repositories": 1
        },
        "Kotlin": {
            "total-dependents": 14,
            "total-stars": 550,
            "total-repositories": 16
        },
        "Smarty": {
            "total-dependents": 0,
            "total-stars": 137,
            "total-repositories": 1
        },
        "Scala": {
            "total-dependents": 0,
            "total-stars": 417,
            "total-repositories": 7
        },
        "Erlang": {
            "total-dependents": 0,
            "total-stars": 148,
            "total-repositories": 3
        },
        "ANTLR": {
            "total-dependents": 0,
            "total-stars": 97,
            "total-repositories": 1
        },
        "Handlebars": {
            "total-dependents": 65,
            "total-stars": 167,
            "total-repositories": 2
        },
        "Haskell": {
            "total-dependents": 0,
            "total-stars": 93,
            "total-repositories": 2
        },
        "Pascal": {
            "total-dependents": 0,
            "total-stars": 96,
            "total-repositories": 2
        },
        "Elixir": {
            "total-dependents": 0,
            "total-stars": 90,
            "total-repositories": 2
        },
        "JSONiq": {
            "total-dependents": 0,
            "total-stars": 63,
            "total-repositories": 1
        },
        "Haxe": {
            "total-dependents": 0,
            "total-stars": 58,
            "total-repositories": 1
        },
        "Svelte": {
            "total-dependents": 4,
            "total-stars": 68,
            "total-repositories": 3
        },
        "JSON": {
            "total-dependents": 0,
            "total-stars": 47,
            "total-repositories": 2
        },
        "Groovy": {
            "total-dependents": 0,
            "total-stars": 75,
            "total-repositories": 4
        },
        "Elm": {
            "total-dependents": 0,
            "total-stars": 70,
            "total-repositories": 3
        },
        "CSS": {
            "total-dependents": 0,
            "total-stars": 48,
            "total-repositories": 3
        },
        "Dockerfile": {
            "total-dependents": 0,
            "total-stars": 35,
            "total-repositories": 4
        },
        "ReScript": {
            "total-dependents": 2,
            "total-stars": 20,
            "total-repositories": 1
        },
        "Racket": {
            "total-dependents": 0,
            "total-stars": 17,
            "total-repositories": 1
        },
        "Jsonnet": {
            "total-dependents": 0,
            "total-stars": 19,
            "total-repositories": 2
        },
        "Smalltalk": {
            "total-dependents": 0,
            "total-stars": 16,
            "total-repositories": 1
        },
        "TeX": {
            "total-dependents": 0,
            "total-stars": 16,
            "total-repositories": 1
        },
        "XSLT": {
            "total-dependents": 6,
            "total-stars": 13,
            "total-repositories": 1
        },
        "PureScript": {
            "total-dependents": 0,
            "total-stars": 11,
            "total-repositories": 1
        },
        "Makefile": {
            "total-dependents": 0,
            "total-stars": 9,
            "total-repositories": 1
        },
        "CoffeeScript": {
            "total-dependents": 0,
            "total-stars": 8,
            "total-repositories": 1
        },
        "XQuery": {
            "total-dependents": 0,
            "total-stars": 8,
            "total-repositories": 1
        },
        "Perl": {
            "total-dependents": 0,
            "total-stars": 7,
            "total-repositories": 1
        },
        "Common Lisp": {
            "total-dependents": 0,
            "total-stars": 6,
            "total-repositories": 1
        },
        "Vala": {
            "total-dependents": 0,
            "total-stars": 6,
            "total-repositories": 1
        },
        "Objective-C": {
            "total-dependents": 0,
            "total-stars": 6,
            "total-repositories": 1
        },
        "Batchfile": {
            "total-dependents": 0,
            "total-stars": 6,
            "total-repositories": 1
        },
        "ColdFusion": {
            "total-dependents": 0,
            "total-stars": 6,
            "total-repositories": 1
        },
        "PowerShell": {
            "total-dependents": 9,
            "total-stars": 10,
            "total-repositories": 2
        },
        "Dart": {
            "total-dependents": 0,
            "total-stars": 5,
            "total-repositories": 1
        },
        "Crystal": {
            "total-dependents": 0,
            "total-stars": 4,
            "total-repositories": 1
        },
        "M4": {
            "total-dependents": 0,
            "total-stars": 4,
            "total-repositories": 1
        },
        "GDScript": {
            "total-dependents": 0,
            "total-stars": 4,
            "total-repositories": 1
        }
    },
    "calculation-date": "2023-11-07 20:49:16"
}
```

**Comment by Relequestual** [comment]
I've created a repo for this work https://github.com/json-schema-org/ecosystem

**Comment by Relequestual** [comment]
> Do we know how "dependents" is calculated? It might be more or less useful depending on how it works. For example, ajv is used by eslint. Would every project that uses eslint be considered a dependent? That would create a lot of noise making it not a very useful metric.

I think we can look for directly depended on vs being a transitive dependency.
That might actually be pretty interesting and to see if that differes across languages.
Although, I suspect javascript/node.js has more dependancy trees than most other languages.

**Comment by benjagm** [comment]
> The first three [Issues](https://github.com/json-schema-org/ecosystem/issues) in the ecosystem repo cover:

Do you like to get help on those issues?

**Comment by Relequestual** [comment]
> > The first three [Issues](https://github.com/json-schema-org/ecosystem/issues) in the ecosystem repo cover:
> 
> Do you like to get help on those issues?

Yes. I think I should commit the work I have done so far on a branch. I probably should not spend much more time on this. I will spend a little more time. I think it is working but I need to run it and wait for it to complete.

**Comment by Relequestual** [comment]
I have pushed some code to https://github.com/json-schema-org/ecosystem/tree/main/projects/initial-data
It runs and produces results, but it has limitations that need addressing.
So far, the code only gathers initial data, and not ongoing data via actions.

**Comment by Relequestual** [comment]
> > The first three [Issues](https://github.com/json-schema-org/ecosystem/issues) in the ecosystem repo cover:
> 
> Do you like to get help on those issues?

I've added some new Issues and details to existing Issues where required.
See https://github.com/json-schema-org/ecosystem/issues/1
Help now welcome. Feel free to communicate this to anyone hungry to contribute =]

**Comment by aialok** [comment]
Hey maintainers! I am really interested in this project. It looks cool to me, especially working with APIs and backend stuff. I love to work on this with you. Currently, I am researching and checking out the codebases. I will ping you once I am done with some good work. I am ready to work on these issues: https://github.com/json-schema-org/ecosystem/issues.

**Comment by benjagm** [comment]
Should we close this issue to continue the work in the ecosystem repo?

**Comment by benjagm** [comment]
Let's continue the discussion in the Ecosystem repo. Thank you all!

https://github.com/json-schema-org/ecosystem
