### ISSUE TITLE
Document use of CommonRoom and Orbit

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#571]
**GitHub Discussion:** # / NA

**Summary**: We should document in our infastructure document that we are using CommonRoom and Orbit for community metrics.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**
No

**Details**: See https://github.com/json-schema-org/community/blob/main/INFRASTRUCTURE.md

**Required to resolve**

- [ ] Update infastructure document

**Comment by benjagm** [comment]
Close as #572 has been merged.
