### ISSUE TITLE
Fix the action item that add items to the agenda of OCWM to remove the label 'agenda' once the item has been added

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#595]
**GitHub Discussion:** # / NA

**Work Summary**:
Fix the action item that add issues and discussions to the agenda of OCWM to remove the label 'agenda' once the item has been added. As of now this needs to be done manually generating some issues because of items added again the week after if the label is not removed on time.

The code to modify is: community/.github/workflows /ocwm-issue-collector.yml

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by Adity20** [comment]
Hi @benjagm Can I take up this one?

**Comment by nikhilyadav24** [comment]
Hey @benjagm can I work on this issue?

**Comment by benjagm** [comment]
Please sync with @utnim2. He did almost all the work in #632 . We only need a change to update discussions using GraphQL. You can review the PR, find the solution and add the suggested change to @utnim2 PR.

**Comment by Adity20** [comment]
Okay @benjagm thanks for the update:)

**Comment by benjagm** [comment]
@Adity20 can you please take ownership of this issue to complete the pending changes?

**Comment by Adity20** [comment]
Sure @benjagm done.
