### ISSUE TITLE
Google Summer of Code 2024 - Call for Project Ideas and Mentors

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#596]
After a fantastic experience in 2023, Google Summer of Code is back and we are looking for project ideas and mentors! 

## What is Google Summer of Code

[Google Summer of Code](https://summerofcode.withgoogle.com/) (GSoC) is a global, online mentoring program focused on introducing students and new contributors to open source software development. GSoC contributors work on a 10-22 weeks programming project with the guidance of mentors from their open source organization. During GSoC, participating contributors are paired with mentors from open source organizations, gaining exposure to real-world software development techniques. 

## Why participating in GSoC?

As an Open Source project, we are committed to support the global developer community to mentor new generations of engineers and this is exactly what GSoC is doing. In addition, we have a lot of great ideas and features that can improve and strengthen the JSON Schema Ecosystem but not enough contributors to join us and pick them up. 

By applying to GSoC we expect to welcome new community members to learn from them and help them be successful in their careers with building together the future of JSON Schema.

## What we need to apply to the program?

We need to co-create a list of the project ideas can produce the best impact in the JSON Schema Ecosystem and make sure we have experienced mentors to provide the best mentoring experience.

## Project ideas

GSoC project ideas are coding projects that potential GSoC contributors can accomplish in about 10-22 weeks. The coding projects can be new features, validators, generators, tooling, frontend enhancements, automations etc. Anyone can submit a project idea, but of course we like it even better if you mentor your project idea.

Please send us your project ideas before February 6th so they can get a proper review in the next **Open Community Weekly Meeting the next 2022-02-05 at 14:00 PT**.

### How to submit a project idea
Create a new issue in this repository using the GSoC Project Idea template and label it with the label **gsoc**. 

**Check for the submitted project ideas** [here](https://github.com/json-schema-org/community/issues?q=is%3Aopen+label%3Agsoc+sort%3Acreated-desc)

Expected format:
- Project Title
- Brief Description
- Expected Outcomes
- Skills Required
- Mentor/mentors
- Expected Difficulty
- Expected Time Commitment

Looking for examples? Check [here](https://github.com/scalacenter/GoogleSummerOfCode2022)

Check for the submitted project ideas of past editions [here](https://github.com/json-schema-org/community/issues?q=is%3Aclosed+label%3Agsoc+sort%3Acreated-desc)

## Mentors expectations

- Be passionate about JSON Schema.
- Lead the project in the area of their interest.
- Actively participate in the project during GSoC Contributor selection, community bonding and coding phases (March - August)
- Dedicate a consistent and significant amount of time, especially during the coding phase (~5 hours per week in a team of two mentors).
- Ideally work in teams of 2+ mentors per 1 each GSoC Contributor.
- Fill in the Google provided final evaluations at the end of the coding period.

### How to show your interest to become a mentor?

It is as simply as adding a comment to this issue.

## Communication:

For any question please reach out in **[#gsoc](https://json-schema.slack.com/archives/C04MVQSRBRS)** Slack channel.

**Comment by jviotti** [comment]
I'd like to be a mentor and can definitely dedicate the required time.

**Comment by benjagm** [comment]
> I'd like to be a mentor

That's amazing. Thanks Juan!

**Comment by benjagm** [comment]
I am planning to be a mentor as well!

**Comment by Julian** [comment]
Same here, definitely a good experience. Will post some ideas!

**Comment by jdesrosiers** [comment]
I'd like to be a mentor as well.

**Comment by benjagm** [comment]
Thanks everyone. I just added 2 project ideas from my side.
