### ISSUE TITLE
Send notifications of failed GitHub actions to a new channel on Slack.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#638]
## Context
The JSON Schema community has been growing rapidly in recent years, and as a result, our community operations have become more complex. While we've made strides in improving our processes and communication, there is always room for improvement. To that end, We'd like to start a discussion around identifying suitable automations that could help us to focus on generating value for JSON Schema.

## Requirements
We'd like to notify in the github slack channel when Github actions fails.

**Comment by Era-cell** [comment]
like failed github actions of what repositories or branch ? or all?

**Comment by pi600** [comment]
Hey can i work on this issue. The issue is in Triage status right now but would love to work on it if it become available

**Comment by Min2who** [comment]
@benjagm I guess this pr #636 solve it . A look will be appreciated

**Comment by benjagm** [comment]
> like failed github actions of what repositories or for all branch ? ..

website and community repositories.
