### ISSUE TITLE
[Bug] Action to send Community Meeting reminders failed

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#640]
**Work Summary**:
The github action used to send Slack reminders of the Open Community Working Meeting the same day failed today:

- Error: https://github.com/json-schema-org/community/actions/runs/8051176516
- Action source code:  https://github.com/json-schema-org/community/blob/main/.github/workflows/ocwm-reminders.yml

Completing this work will mean reminders are sent every monday before the meeting as per the scheduling instruction provided in the action.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by aialok** [comment]
@benjagm  I would love to work on this issue.
Thank You : )

**Comment by aialok** [comment]
@benjagm, 10 hours ago, @octokit/core released a new version of its package. This might be the reason for the workflow failure.

**Comment by benjagm** [comment]
Thanks @aialok . Please go ahead with this fix.

**Comment by benjagm** [comment]
Same issue failed today in other github action: https://github.com/json-schema-org/community/issues/644

**Comment by aialok** [comment]
> Same issue failed today in other github action: #644

This is definitely because of new version release of `@octokit/core`.

**Comment by benjagm** [comment]
Please go ahead with fixes.
