### ISSUE TITLE
[Bug] Action to to create Open Community Working Meeting failed

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#644]
Work Summary:
The github action used to create Open Community Working Meeting failed today:

See issue #640 . Issue is the same.

Error: https://github.com/json-schema-org/community/actions/runs/8062344014

Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)

No

**Comment by princerajpoot20** [comment]
@benjagm I would like to work on this

**Comment by benjagm** [comment]
Thanks @princerajpoot20 . Mintu is going complete the work he started in #640

**Comment by benjagm** [comment]
Sure. Please do check the solution that is going to be applied in #640
