### ISSUE TITLE
GSoC : A tour of JSON Schema

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#645]
**GSoC : A tour of JSON Schema**

**Brief Description**
JSON Schema is easy and difficult at the same time and get expertise with it requires time, good docs and support from the community. With this project we intend to make it easier this process easier and quicker for new JSON Schema users.

What do you think about building an interactive learning material for json schema, similar to tour.golang ( https://go.dev/tour/welcome/1) ? It would be a sequence of tasks, every task would be about authoring a json schema document, that fulfills a textually provided requirement? Then the site would automatically validate / test the solution of the user.

**Expected Outcomes**
A new website called "A tour of JSON Schema" providing a learning experience for new JSON Schema users, similar than the learning experience https://go.dev/tour/welcome/1 provides to new Golang users. This will be a client-side/SPA javascript application that we can run as github pages.

**Mentors**
@erosb @benjagm 

**Expected Difficulty**
Medium

**Expected Time Commitment**
175 hours

**Comment by nouralmulhem** [comment]
Hey, I'm interested contributing to this, I've implemented a similar tool before a small compiler using wordpress on an internship before but i would like to dive into this problem again using different technologies, as it will be a new project so is there any qualification tasks for that one?
this is my resume it includes my experience in front-end development, let me hear you thoughts about qualification tasks, some small demo for this, or even your recommendation to start building and sharing a draft proposal [[link](https://drive.google.com/file/d/1usWA6FpAp4ZFnZb5Q9N1Iuh0vVqjQk1f/view)]

**Comment by Adity20** [comment]
Hi @benjagm I'm eager to contribute to this issue and help create an interactive learning platform for JSON Schema. I have experience with front-end development using TypeScript and React and I'm excited to lend my skills to this project.
For the expected outcomes, a website similar to the Go tour, but tailored for JSON Schema, would be an excellent resource for the community. It would provide a structured and engaging way for users to learn and practice JSON Schema concepts.
It can indeed significantly ease the learning curve for newcomers to JSON Schema and provide them with hands-on experience in crafting schemas to meet specific requirements.

**Comment by VivekJaiswal18** [comment]
Hello @benjagm what will be the qualification task for this project idea?

**Comment by benjagm** [comment]
Hi everyone! Find below the **details of the qualification task**:

Create a simple project with similar design to [json-schema.org](http://json-schema.org/). Start with a welcome page and a button to start, to later build this multi step **experience**: 
- Step 1 : Ask the user to provide a JSON Schema and validate if is valid for Draft 2020-12.
Once the user completes step 1 take them to step 2
- Step 2 : Ask the user to provide a JSON Schema that defines and array with items of type number and validate it.

**Requirements**:
- The app will use a json schema and a json for defining steps (with description and testcases), this is what you will use to build the multi-step experience.
- Providing a code editor to allow users to provide the json schema to be validated.

Good luck!!

**Comment by youseftrek** [comment]
Hi there,

I came across your project proposal for "A Tour of JSON Schema" and I must say, it's an exciting initiative that aligns perfectly with my skill set and interests. My name is **Yousef Tarek**, and I'm a passionate developer proficient in React, Next.js, JavaScript, Tailwind CSS, and with a strong focus on UI/UX design and creating interactive user interfaces.

Having worked extensively with these technologies, I am confident in my ability to contribute effectively to the development of the "A Tour of JSON Schema" website. My experience in React and Next.js ensures that I can efficiently implement the front-end features and functionalities required for the interactive learning platform. Additionally, my expertise in UI/UX design and Tailwind CSS allows me to create visually appealing and intuitive user interfaces that enhance the learning experience.

I'm particularly excited about the opportunity to leverage my skills to help make learning JSON Schema more accessible and engaging for newcomers. I believe that my background in front-end development and design, coupled with my passion for creating educational resources, makes me well-suited to contribute meaningfully to this project.

I'm eager to collaborate with you and the rest of the team, and I'm committed to delivering high-quality code and contributing positively to the project's success. Please let me know how I can get involved and contribute to the GitHub repository for "A Tour of JSON Schema."

Looking forward to the possibility of working together!

Best regards,
Yousef Tarek

**Comment by vinfinity7** [comment]
Hello @benjagm @erosb ,

- I came across your project proposal for "A Tour of JSON Schema," ! I'm Saksham Misra, a developer with a knack for Typescript , React, Next.js, JavaScript, Tailwind CSS, Windi and a lot more .

- With learning excitement I can deal with any Framework I deal with  including Electron js , Next js , React js or Three sj . I am well-prepared to tackle the challenges of GSOC'24 confidently. My dedication to open source contributions has been a longstanding passion, driving me to continually enhance my skills and contribute meaningfully to the community.

- Honestly , During my tenure with your team, I plan to immerse myself in learning C++. This endeavor is driven by my ambition to develop an emulator, a project that will not only expand my skill set but also contribute significantly to the goals of the organization .

- I am planning onto finishing the qualification task as quickly as I can inorder to proceed myslef to form the roadmap for my GSOC application .

**Comment by officeneerajsaini** [comment]
> We just added a new skill required: Ability of applicants to create enjoyable learning material.

It's a most important skill for this project @benjagm ✨

**Comment by kunal0607** [comment]
Hello @benjagm @erosb,

I'm excited about contributing to the "A Tour of JSON Schema" project, bringing to the table my strong background in both backend development and front-end technologies, including Next.JS and TypeScript. My experience in setting up databases, creating APIs, and working with server-side logic complements my proficiency in front-end development, allowing me to contribute to a wide range of tasks within the project. I'm particularly keen on leveraging these skills to help build a robust, interactive learning platform that offers an engaging and seamless experience for users delving into JSON Schema.

Looking forward to the opportunity to contribute to this innovative project and the community.

Best regards,
Kunal Bansal

**Comment by benjagm** [comment]
Hi everyone!  We just updated the Project requirement adding the following requirements:

- Expected Outcomes: This will be a client-side javascript application that we can run as github pages.
- Skills Required:
   - This task is ideal for someone creative with a sense for UI/UX.
   - ~~Front-end development with familiarity with Typescript, React and Next.js.~~
   - Front-end with javascript.
   - Ability of applicants to create enjoyable learning material.

**Comment by suryagowda** [comment]
@benjagm Regarding qualifying task, Draft 2020 12 json schema validating is breaking and I couldn't able to find a valid meta schema for it...instead can we use draft 7 or any previous version?

**Comment by officeneerajsaini** [comment]
> @benjagm Regarding qualifying task, Draft 2020 12 json schema validating is breaking and I couldn't able to find a valid meta schema for it...instead can we use draft 7 or any previous version?

Yes @suryagowda i am facing same issue

**Comment by benjagm** [comment]
> @benjagm Regarding qualifying task, Draft 2020 12 json schema validating is breaking and I couldn't able to find a valid meta schema for it...instead can we use draft 7 or any previous version?

Can you share the full text and the validator you are using?

**Comment by khoatr1509** [comment]
Hello @benjagm, I hope this message finds you well. I recently joined this disscussion and am eager to contribute to the qualifying tasks. Given my late start, I was wondering if there's a possibility for me to work on them. I'm genuinely enthusiastic about the project and excited about the opportunity to enhance the UX/UI. 
Looking forward to your guidance and the chance to bring something cool to the table

**Comment by benjagm** [comment]
> Hello @benjagm, I hope this message finds you well. I recently joined this disscussion and am eager to contribute to the qualifying tasks. Given my late start, I was wondering if there's a possibility for me to work on them. I'm genuinely enthusiastic about the project and excited about the opportunity to enhance the UX/UI. Looking forward to your guidance and the chance to bring something cool to the table

Welcome Khoa! Please see the qualification task for this project:

https://github.com/json-schema-org/community/issues/645#issuecomment-1973742879

**Comment by suryagowda** [comment]
@benjagm Would you like to provide any feedback for the qualification task which I completed. If yes , where can I send you the project?

**Comment by V1K1NGbg** [comment]
Hello @benjagm. 
My name is Victor Ilchev. I am a first-year student at the Technical University of Delft. I have a passion for learning and developing my skills. This is why I am eager to contribute to this project. 
This brings me to my questions:
1. How can I prepare to be a valuable part of your team?
2. How do I begin to contribute to this project?
If you want to know more about me, you can check out my GitHub profile.
Thank you for your time!

**Comment by erosb** [comment]
Helo @V1K1NGbg , welcome to the json schema community!

You can complete the [qualification task](https://github.com/json-schema-org/community/issues/645#issuecomment-1973742879) , then
 * push your code into a github repo
 *  and deploy it somewhere (for example a github page) 
 * let us know about the previous two

You can also reach out to us on Slack.

**Comment by khoatr1509** [comment]
Hi @benjagm and @erosb, I just finish the qualify task, could you please share me the Slack link again. I have no idea where to find it. Thank you very much!

**Comment by benjagm** [comment]
@khoatr1509 please use [this link](https://json-schema.org/slack) to join and send us a group DM with the repo and the url to test it. Thanks!

**Comment by benjagm** [comment]
🚩 **IMPORTANT INSTRUCTIONS REGARDING HOW AND WHERE TO SUBMIT YOU APPLICATION** 🚩

Please join this discussion in JSON Schema slack to get the last details very important details on how to better submit your application to JSON Schema.

See communication [here](https://json-schema.slack.com/archives/C04MVQSRBRS/p1710754267174439).

**Comment by harini-1597** [comment]
Hey @benjagm @erosb
New here, but I'm very excited to work on this. In the process of learning Web Development and this would serve as a great first full-stack application that I'd build! I'll be using HTML, TypeScript, ReactJS, NextJS & Tailwind CSS for this.
Since the developer community practically thrives on open-source, it would be pretty amazing to contribute to code that would be used and implemented by others.
Looking forward to working with everyone!

**Comment by JeelRajodiya** [comment]
> Hi everyone! We just updated the Project requirement adding the following requirements:
> 
> * Expected Outcomes: This will be a client-side javascript application that we can run as github pages.
> * Skills Required:
>   
>   * This task is ideal for someone creative with a sense for UI/UX.
>   * ~Front-end development with familiarity with Typescript, React and Next.js.~
>   * Front-end with javascript.
>   * Ability of applicants to create enjoyable learning material.
> 
> We are removing the option of building a server-side app, instead we'll prefer a native client-side javascript/SPA app that we can run as github pages.

Can we use typescript for the project? Is it mandatory to use JavaScript?

**Comment by erosb** [comment]
@JeelRajodiya typescript is preferred over javascript

**Comment by JeelRajodiya** [comment]
One more question. 
I have a basic project ready with a decent-looking UI.
Should I prioritize the user interface and additional features in the qualification task? Do they play a role in the evaluation process?

**Comment by Lahu19** [comment]
Hello everyone, I'm happy to join the open-source community! While I'm new to contributing, I've already built several projects in full-stack development. I'm particularly passionate about contributing to this project and am currently focused on enhancing the UI for the Tour of JSON Project.

**Comment by Piyusharora2003** [comment]
hi @benjagm 
I am interested in working on this project.
I have experience with front-end development using React and I'm excited to lend my skills to this project. For the expected results,  an interactive way to learn and understand JSON Schema  i believe my skills would be relevant for the project .

I would love to contribute to this Project Idea in the coming summer for GSoC! Thanks.

**Comment by JARViSmakesitEZ** [comment]
Hello @benjagm , I am a 3rd year Computer Science Engineering student and I am really interested in working on this project.I have an approach on how to work on this and it is as  follows:

Features:
Task-based Learning: The platform will present users with a sequence of tasks, each focusing on a specific aspect of JSON Schema authoring.
Textual Requirements: Users will be provided with clear and concise textual requirements for each task, guiding them on what needs to be achieved.
Interactive Editor: An interactive editor will be provided for users to author their JSON Schema documents directly within the platform.
Automatic Validation: Upon submission of a solution, the platform will automatically validate the JSON Schema document against the provided requirements.
Feedback and Testing: Users will receive immediate feedback on their solutions, including any errors or discrepancies found during validation. Additionally, automated testing will be performed to ensure the correctness and completeness of the solution.
Progress Tracking: Users will be able to track their progress through the learning material, enabling them to revisit previous tasks and monitor their overall proficiency in JSON Schema.
Implementation Plan:

Platform Design: Design the user interface and overall structure of the interactive learning platform.
Task Creation: Develop a series of tasks, each focusing on different aspects of JSON Schema authoring. Tasks will be designed to progressively increase in complexity.
Interactive Editor: Implement an interactive editor that allows users to author JSON Schema documents directly within the platform.
Validation and Testing: Integrate validation and testing mechanisms to automatically validate user-submitted solutions against provided requirements.
Feedback System: Develop a feedback system to provide users with immediate feedback on their solutions, highlighting any errors or discrepancies.
Progress Tracking: Implement features for users to track their progress through the learning material and monitor their proficiency in JSON Schema.

Timeline:
Week 1-2: Platform design and task creation
Week 3-4: Interactive editor implementation
Week 5-6: Validation and testing integration
Week 7-8: Feedback system development
Week 9-10: Progress tracking implementation
Week 11-12: Testing, refinement, and finalization

The development of an interactive learning platform for JSON Schema will provide an invaluable resource for novice users seeking to master this powerful tool. By simplifying the learning process and providing immediate feedback and guidance, we can empower users to become proficient in JSON Schema authoring in a more efficient and engaging manner.

Best Regards,
Gourav Ghosh

**Comment by programmerjavascript** [comment]
Hi Ben (@benjagm),

Hope this message finds you well! I'm Njamen Ulrich, a junior web and mobile developer with a strong passion for JavaScript.

I recently registered for the google summer of code and was immediately drawn to its goal of making JSON learning accessible. As you mentioned, JSON can be both easy and challenging to grasp, especially without proper guidance.

That's where I believe my skills can be valuable:

Web Development: I have a solid foundation in web development principles, allowing me to contribute to the website's structure and functionality.
MongoDB: My familiarity with MongoDB, a popular NoSQL database that heavily utilizes JSON, provides me with insights into practical JSON applications.
Object-Oriented Programming (JavaScript): My knowledge of object-oriented programming in JavaScript, a language commonly used with JSON, strengthens my ability to understand and implement JSON features effectively within the website.
Postman and Node.js for Building APIs: I have experience using tools like Postman and Node.js, which are frequently used to interact with APIs that often exchange data in JSON format. This experience allows me to offer a perspective on demonstrating real-world use cases within the website.
I'm eager to leverage my skills and collaborate with the team. My enthusiasm for learning and contributing can significantly enhance the website's educational value.

Thank you for your time and consideration.

Best regards,

Njamen Ulrich

**Comment by radhesh1** [comment]
Hi Benja
Is there any Progress on this?
