### ISSUE TITLE
How to apply mandatory key values under array of Object and also allow new optional values ?

### ISSUE THREAD

**Issue by chaitanyak4888** [json-schema-org/community#650]
### Discussed in https://github.com/orgs/json-schema-org/discussions/649

<div type='discussions-op-text'>

<sup>Originally posted by **chaitanyak4888** March  1, 2024</sup>
{
    "test": {
        "bundle": [
            {
                "account": {
                    "accountType": "Savings",
                    "somekeyc": "testc"
                }
            },
            {
                "account": {
                    "accountType": "Current",
                    "somekeya": "testa"
                }
            },
            {
                "account": {
                    "accountType": "Loan",
                    "somekeyb": "testb"
                }
            }
        ]
    }
}
 I need accountType as required field and the values of it should be "Loan" and "Savings" both these two arrays  should be present for a given Json to validate if not throw it as invalid Loan and Savings are missing from the Array. And  accountType  should allow new values other than the two mentioned.   Please help me out. I tried with enum , required and oneOf condition but could not get the exact solution for this. </div>

**Comment by Era-cell** [comment]
So, there should be minimum 2 items  one of them should have "Savings" and one should have "Loan" atleast. Am I right?

**Comment by jdesrosiers** [comment]
Closing as duplicate. Answered in https://github.com/orgs/json-schema-org/discussions/649.

**Comment by chaitanyak4888** [comment]
Yes , there should be two object minimum and one should have savings and other should be of loan. And also it should allow new values which are not declared in json schema.


> So, there should be minimum 2 items one of them should have "Savings" and one should have "Loan" atleast. Am I right?
