### ISSUE TITLE
Enhancement: Create issue templates for Bugs and Enhancements like we have in the website repo

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#656]
It will be to create 2 new issue templates in the community repo to be able to notify bugs in Community workflows and to suggest new community workflows (Github actions to automate community ops).

We can use as reference:
https://github.com/json-schema-org/website/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml
https://github.com/json-schema-org/website/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml

But removing unnecessary fields and focused in community workflows.

**Comment by Ekep-Obasi** [comment]
@benjagm I'd love to work on this 
Could you please assign me?

**Comment by benjagm** [comment]
Thanks @Ekep-Obasi . Please go ahead.

**Comment by ayushtiwari110** [comment]
Hey @benjagm , can I contribute in this issue in someway?

**Comment by ayushtiwari110** [comment]
If there's some work being done already, I can also help in reviewing the PR if this sounds good...

**Comment by benjagm** [comment]
I am leaving this issue available for other contributors

**Comment by Adity20** [comment]
Shall I take this up? @benjagm

**Comment by benjagm** [comment]
Go ahead @Adity20! Thanks

**Comment by benjagm** [comment]
Completed
