### ISSUE TITLE
Enhancement : Create a github action to remind the Office Hours session in Slack

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#663]
**Work Summary**:
It would be great to create a workflow that send reminders to `#general` channel in Slack about the Office Hours session happening the first tuesday of the month at 15:00 BST.

Details of the office hours session: https://github.com/orgs/json-schema-org/discussions/34

Example of reminder:
<img width="512" alt="Screenshot 2024-03-05 at 15 26 04" src="https://github.com/json-schema-org/community/assets/40007659/13d2729b-b56d-4276-89bc-ede955001f54">

When: 
* Reminder to be sent the friday before the session.
* Reminder to be sent the morning on the same day.

Similar workflow:
https://github.com/json-schema-org/community/blob/main/.github/workflows/ocwm-reminders.yml

**Comment by Adity20** [comment]
@benjagm I want to work on this one. Can you please assign this to me?

**Comment by benjagm** [comment]
@Adity20 thanks! please go ahead.

**Comment by Maykkkk** [comment]
Hey @Adity20 , I would love to contribute in this issue are you still working on it?

**Comment by Adity20** [comment]
Yes I am working on it @Maykkkk  already raised a PR also.

**Comment by benjagm** [comment]
Completed.
