### ISSUE TITLE
[📝 Docs]: Remove references to OpenJS Foundation in the community repo.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#664]
### What Docs changes are you proposing?

We'd like to remove all the references to OpenJS foundation in the community repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Akshaybagai52** [comment]
Hey @benjagm can you assign this issue to me

**Comment by Akshaybagai52** [comment]
> of course. Thanks @Akshaybagai52 !!

Thanks

**Comment by Akshaybagai52** [comment]
> of course. Thanks @Akshaybagai52 !!

This is PR link https://github.com/json-schema-org/community/pull/670

**Comment by benjagm** [comment]
@Relequestual Should we remove the file https://github.com/json-schema-org/community/blob/main/docs/openjsf/application.md?

**Comment by wcj617** [comment]
HI, @benjagm 
Can I also join this issue?

**Comment by Akshaybagai52** [comment]
> HI, @benjagm Can I also join this issue?

Hello @wcj617 
This issue is on hold you can try contributing on other issue.
Thanks

**Comment by heysujal** [comment]
@benjagm After reading the mentioned PR #670  conversations. I think this issue should be closed.

**Comment by benjagm** [comment]
That is right. Thanks @heysujal
