### ISSUE TITLE
🐛Bug/Maintenance: Updating actions which are on deprecated Node version

### ISSUE THREAD

**Issue by ayushtiwari110** [json-schema-org/community#675]
**GitHub Discussion:** website repo/issue-539

**Work Summary**:

In the GitHub Discussion, @benjagm asked that we need to upgrade the deprecated github actions of the community repo.

As a result, we need to update the following worklows which are deprecated:
- Close issues with no tasks and a specific label:
![close issue no task](https://github.com/json-schema-org/community/assets/84335414/2c6fe7d2-f4c4-4197-8796-6d92bae8a4db)
- Create OCWM weekly:
![ocwm](https://github.com/json-schema-org/community/assets/84335414/3eca4d6c-6008-43c0-b70a-6e4419b39471)
- Search for issues and PR labeled 'agenda' and add them to the agenda:
![image](https://github.com/json-schema-org/community/assets/84335414/467a3fbb-8f33-4352-822c-38c2aa00329d)

Completing this work will mean that all our workflows are using latest Node.js version, hence the warnings shown by github in the actions dashboard will be resolved!

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No
[JUSTIFICATION]

**Work Detail**:

- Updating the versions of various github actions which are using deprecated Node version

**Any further requirements to resolve this issue**
No

**Comment by ayushtiwari110** [comment]
Hi there @benjagm . Can I start working on this issue. It's a short issue, and I 've worked on similar issue in website repo , and also on other cicd tasks.

**Comment by benjagm** [comment]
Go ahead @ayushtiwari110 . Thanks!

**Comment by ayushtiwari110** [comment]
@benjagm , I have raised a PR for this issue. Kindly have a look at it when you get a moment. Thanks! 🚀
