### ISSUE TITLE
Ambassadors Program - Requisites and budget

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#678]
This document covers the organizational and operational aspects of the JSON Schema Ambassadors Program.

### What is the JSON Schema Ambassador Program?

The JSON Schema Ambassador Program aims to bring JSON Schema closer to both current users and potential new project users. It also aims to provide users and community members with the necessary tools and resources to:

- Promote collaboration among the JSON Schema ecosystem.
- Promote JSON Schema adoption in other ecosystems.
- Engage with the project in some way, either as a contributor, blogger, speaker, etc.
- Speak at community events or write technical content (e.g. blog posts) that solves community needs.
- Nurture community growth and a welcoming environment to spread knowledge about the project.

Requisites:
- For this program to be launched we need the swag kits available so it will be necessary to have that ready first.
- The cost estimation will be confirmed in the next weeks.

**Comment by benjagm** [comment]
The expected cost of the online store and the swag is:

| Budget Item | Cost  in €
| -- | -- |
| Online Shop (Development) |	398 |
| Online Shop Hosting (Yearly) | 1.200|
| Swag (Yearly)| 5.000|
| Swag Storage  (Yearly)| 1.000|
| Total | 7.958 |

**Comment by radhesh1** [comment]
Sounds Interesting!

**Comment by benjagm** [comment]
Hi everyone!

I have been thinking about different alternatives to reduce the costs of the swag+shop project focused on Prin-on-demand + Shopify subscription to reduce the costs as much as possible. Using this approach the estimated costs reduction will be almost 50% which is a amazing for a small organization like us so definitely this is the path I'll like to take:

The expected cost of the online store and the swag following this approach is:

| Budget Item | Cost  in €
| -- | -- |
| Swag (Yearly)| 2.520 |
| Delivery costs | 400 |
| Shopify subscription | 324 |
| Designer for stickers / badges | 1000 |
| Total | 4.244 |
