### ISSUE TITLE
issues: #931

### ISSUE THREAD

**Issue by neehhaa06** [json-schema-org/community#682]
**GitHub Discussion:** # / NA

**Work Summary**:

In the GitHub Discussion, we concluded that...

As a result, we need to...

Completing this work will mean...

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

**Work Detail**:

- [x] List of work
- [ ] To be done

**Any further requirements to resolve this issue**

**Comment by benjagm** [comment]
Thanks for creating a new issue. Can you provide more details ?

**Comment by neehhaa06** [comment]
> Thanks for creating a new issue. Can you provide more details?

yes, I will assure you!
