### ISSUE TITLE
Proposal to add git-vote to better automation around TSC voting and participation tracking

### ISSUE THREAD

**Issue by aialok** [json-schema-org/community#742]
### Description:

We are currently managing the voting process manually. Using `git-vote` will automate this process and help in tracking participation more easily. `git-vote` assists in creating voting processes on issues or pull requests and provides several commands to simplify the voting process.

We need to set up the `git-vote` GitHub app. This GitHub app is maintained by the same maintainer who manages the `landscape` project.

https://github.com/cncf/gitvote

### Commands:
- `/vote`: This command initiates the voting process and can only be executed by collaborators of the repository.
- `/check-vote`: This command checks the status of votes. It provides information on how many participants have voted, how many are remaining, and the percentage of voting completed so far, and comments this in the issue or pull request.
- `/cancel-vote`: This command is used to cancel the voting process if we need to close it prematurely.

Once the voting period is up, the vote will automatically close, and the results will be published in a new comment.

Here is a good example of `git-vote` used by  AsyncAPI : 
- [chore: add Marketing WORKING_GROUP](https://bit.ly/3V9CdiV).
- [How voting automation works in Async-Api?](https://github.com/asyncapi/community/blob/master/voting.md)

### Steps to Implement:
1. Install the `git-vote` GitHub app.
2. Setup the [.gitvote.yml](https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml) configuration file.
3. Document how the voting automation works.

This will provide a better way of making decisions. When we use `/check-vote`, it will mention every team member, sending notifications automatically without the need to manually ping any members.

**I would like to hear the thoughts of the maintainers on automating the voting process.**

**Comment by Relequestual** [comment]
The only issue we might have currently is we have left votes open longer than the specific time defined. We could mitigate this issue by setting the time to one month for now, and then adjust if needed later.

**Comment by benjagm** [comment]
The app has been installed in the TSC repo.

**Comment by benjagm** [comment]
Closed as completed

**Comment by benjagm** [comment]
Closed as completed.
