### ISSUE TITLE
GSoC 2024 - Success Stories and Application Tips

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/community#753]
We are please of sharing with you the success of stories of the selected contributors for Google Summer of Code 2024 with JSON Schema!

If you are interested on applying to GSoC in the future, this video is for you!

To know more about this year's project please visit: https://github.com/json-schema-org/community/blob/main/programs/mentoring/gsoc/gsoc-2024.md

📺  See the recording in Youtube: https://youtu.be/2V9k1Hqhgnw

- **Divyaditya Singh Naruka**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=99s
- **Pranay Joshi**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=190s
- **Diya Solanki**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=312s
- **Zeel Rajodiya**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=567s
- **Dhruv Singh**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=675s
- **Alok Gupta**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=940s
- **Adwait Godbole**
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=1267s
- **Suprith KG** 
   - 📺  https://www.youtube.com/watch?v=2V9k1Hqhgnw&t=1659s
   
Thanks!

**Comment by kwennB** [comment]
Love this! 🧡✨
