### ISSUE TITLE
Add JSON schema for ambassadors.json

### ISSUE THREAD

**Issue by DavidBiesack** [json-schema-org/community#755]
**Work Summary**:

I suggest this repository include a JSON Schema next to the `programs/ambassadors/ambassadors.json` file (such as`programs/ambassadors/ambassadors-schema.json` ). When adding a submission, I was not sure what values I can use for `contribution.type` - a schema would tell me if it is an `enum` or an open `string` value :slightly_smiling_face: 

Completing this work will mean contributors know how to submit a PR. Plus, this will highlight a good use of JSON Schema.

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Work Detail**:

- [ ] add a JSON Schema for the `ambassadors.json` file
- [ ] Add a github action to validate the `ambassadors.json` file against the schema

**Comment by ramishj** [comment]
I want this task assigned.

**Comment by ramishj** [comment]
Please assign this task to me.

**Comment by benjagm** [comment]
Great idea David. Thanks!

@ramishj are you available to work on this?

**Comment by ramishj** [comment]
yes i have already done it should i push it ? Assign me i will push it

**Comment by ramishj** [comment]
Can you assign it to me?

**Comment by benjagm** [comment]
All yours @ramishj . Thanks a lot for your support!

**Comment by ramishj** [comment]
> All yours @ramishj . Thanks a lot for your support!

Your Welcome

**Comment by Relequestual** [comment]
It looks like this work is done!
@DavidBiesack can you look and confirm if you're happy with the merged PR associated with this Issue please =D

**Comment by DavidBiesack** [comment]
Thank you!
