### ISSUE TITLE
🐛 Bug: Slack Invite Link Not Working

### ISSUE THREAD

**Issue by bflad** [json-schema-org/community#775]
### Describe the bug

When visiting https://json-schema.org/ and clicking the "Join Slack" link or going directly to https://json-schema.org/slack, Slack says the invite link is no longer valid.

![CleanShot 2024-07-22 at 10 56 21](https://github.com/user-attachments/assets/87dd08aa-f284-41a8-8718-286d7995c22d)

### Steps To Reproduce

1. Browse to https://json-schema.org/
2. Click "Join Slack" button link

### Expected Behavior

Slack to allow me to create account and join JSON Schema community Slack workspace.

### Device Information [optional]

```markdown
- OS: macOS 14.5
- Browser: Google Chrome
- version: Version 126.0.6478.127 (Official Build) (arm64)
```

### Are you working on this issue?

No

**Comment by benjagm** [comment]
Thanks for filing this issue @bflad ! We just fixed it. Can you please try again?

**Comment by bflad** [comment]
Worked great, thank you for the quick response!
