### ISSUE TITLE
Define and automate 5 processes on GitHub

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#82]
We would benefit from having automation take care of some basic repetitive tasks we end up doing.
Adding `triage` to every new issue or PR would be a good start.
We should also look to automate our regular Open Community Working Meeting issue, including collecting items to concisder for the agenda from across the org. (This may involve adding tags across all repos.)

**Comment by benjagm** [comment]
Closed in favour of #373

**Comment by benjagm** [comment]
Closed as completed.
