### ISSUE TITLE
Add date to ambassadors data

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#836]
**Summary**: Ambassador status should be reviewed every year, so we need to log the date of issue.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)** No

It is adding data based on what was already defined for the program.

**Details**:

**Required to resolve**

We have a small number of ambassadors. They were added in one or two groups on a specific date, I forget which. @benjagm can bring clarity on the date, or it might be in the slack server history.

- [ ] Add startedOn and lastReviewedOn fields to the schema
- [ ] Add the data for startedOn dates.

I believe this is the best approach as it would be nice to also track how many years they have been an ambassador vs just when they are next up for review.

**Any further requirements to resolve this issue**
Confirm dates are correct with evidence.
The above should be all one PR.

**Comment by jeevansegu** [comment]
I would like to work on this
i was considering if i could add these two fields(startedOn and lastReviewedOn) at the end of the schema after contributions
if that is okay, i would like to ask @benjagm for the dates to add for startedOn and lastReviewedOn
also is the dates in the format of date, month and year or just month and year

**Comment by MohdAbdulSami** [comment]
hi @Relequestual I would also love to work on this issue, but I want to understand how can i go ahead with  solving the issue as its going to be my first time solving

**Comment by Relequestual** [comment]
> @Relequestual I would like to work on this, Please assign this issue to me. i was considering if i could add these two fields(startedOn and lastReviewedOn) at the end of the schema after contributions if that is okay - @jeevansegu 

Sure, go ahead with making a PR!

> i would like to ask @benjagm for the dates to add for startedOn and lastReviewedOn also is the dates in the format of date, month and year or just month and year

You should be able to work this out based on the git history on GitHub. If you're still unsure after that, do as Benja.

Month and year is fine, following what we have already used.

Thanks! =]

**Comment by jeevansegu** [comment]
> > @Relequestual I would like to work on this, Please assign this issue to me. i was considering if i could add these two fields(startedOn and lastReviewedOn) at the end of the schema after contributions if that is okay - @jeevansegu 
> 
> Sure, go ahead with making a PR!
> 
> > i would like to ask @benjagm for the dates to add for startedOn and lastReviewedOn also is the dates in the format of date, month and year or just month and year
> 
> You should be able to work this out based on the git history on GitHub. If you're still unsure after that, do as Benja.
> 
> Month and year is fine, following what we have already used.
> 
> Thanks! =]

I'll look into the git history and reach out to Benja if I have any doubts
Thank you

**Comment by Relequestual** [comment]
> hi @Relequestual I would also love to work on this issue, but I want to understand how can i go ahead with solving the issue as its going to be my first time solving - @MohdAbdulSami 

Thanks for your interest. If you're looking to break into open source, you may find other good first issues issues here: https://goodfirstissue.dev/

**Comment by Relequestual** [comment]
Fixed with #838
