### ISSUE TITLE
Create 3 JSON Schema in Production videos

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#84]
Done: https://www.youtube.com/watch?v=fkziMQD7pqQ&list=PLHVhS4Tj1YZOrrvl7_a9LaBAtst7BWH8a

We want to showcase great examples of JSON Schema in production.
Case studies are a great way to do this, but don't allow for free flowing discussion.
A "chat" / video call with some individuals who have used JSON Schema to great effect in production, provides an alternative medium to learn about JSON Schema.

The target audience might be different, and we would look to focus more on the wins and impact as opposed to technical detail.

- [x] #120
- [x] #121
- [x] #122
- [x] #123

**Comment by kinlane** [comment]
This is great! I suggest focusing on just the basics. Like you said, focus on the wins as opposed to the technical detail. Get the cadence to the show. Get interesting people to come out and talk about what they are doing. Amplify the hell out of it on Twitter, etc. Repeat. Repeat. Repeat. You'll find the flow.

**Comment by kinlane** [comment]
Also, I am happy to do an episode with you and talk about how I used JSON Schema at F5 Networks. It is a compelling story about how to modernize a large volume of XML schema to JSON Schema.

**Comment by Relequestual** [comment]
Tom Laird-McConnell from Microsoft is willing to chat. He works on the BotFramework and has used JOSN Schema "very extensivly".
I am booking an initial call to get to know each other.

**Comment by Relequestual** [comment]
Chuck Reeves, previously full time and currently on contact at Zones, currently full time at Saber Astronautics, is willing to chat. Zones is an IT solutions provider which has worked with many world leading organizations.
Initial intro call done. Questions sent for review.
I will follow up in 1 week if I do not hear back.

**Comment by Relequestual** [comment]
Playlist here: https://www.youtube.com/watch?v=fkziMQD7pqQ&list=PLHVhS4Tj1YZOrrvl7_a9LaBAtst7BWH8a
