### ISSUE TITLE
Case Study: NASA

### ISSUE THREAD

**Issue by kinlane** [json-schema-org/community#88]
I think it would be valuable to the community to write a blog post about how NASA uses the specification.

**Comment by Relequestual** [comment]
No response. Follow up sent.

**Comment by Relequestual** [comment]
Unfortunatly, NASA ESDIS is not able to participate in a JSON Schema case study.
Rejected request having been run up the management chain.

**Comment by Relequestual** [comment]
Pasting references should we wish to try and pick this up again with additional support of OpenJSF for example.

https://twitter.com/relequestual/status/1450777419212861440
https://www.earthdata.nasa.gov/eosdis/science-system-description/eosdis-components/cmr
https://www.earthdata.nasa.gov/unified-metadata-model-umm
